version: '2.2'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    # Add any other environment variables from .env file
    env_file:
      - .env
